### ISSUE TITLE
TODO: C_PWM

### ISSUE THREAD

**Issue by FDSoftware** [openefi/OpenEFI#18]
- [ ] calculo de timer_set_prescaler | tick (para un basetime de 0.5uS)
- [ ] exti0_isr : revisar que corno usar de trigger, si change o falling, falling se ve inestable a mas de 5Khz
- [ ] implementar avance de inyeccion
- [ ] avance de encendido (con funcion aparte?)
- [ ] controlar todo con analizador logico, con entrada de 1Khz y tiempo de 7uS

**Comment by FDSoftware** [comment]
la secuencia esta *horrible*, tengo que pasar todo a grados para que sea más fácil de debuggear
![image](https://user-images.githubusercontent.com/15681280/79036212-7d912400-7b9c-11ea-8326-4548723878ff.png)
